# I don't care for underscores in numbers.
Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/FileName:
  Exclude:
    - 'lib/logstash-output-jdbc_jars.rb'
